libapp/urls.py
from django import views
from django.contrib import admin
from django.urls import path
from libapp import views

app_name = 'libapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.books, name='books'),
    path('books/<int:book_id>', views.detail, name='detail'),
    path('add/', views.add_book, name='add_book'),
    path('update/<int:id>', views.update, name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
    path('register/',views.registerPage,name='register'),
    path('login/',views.loginPage,name='login'),
    path('admin_login/',views.adminloginPage,name='admin_login'),
    path('logout/',views.logoutUser,name='logout'),
    path('members/',views.members,name='members'),
    path('members/<int:id>',views.member_detail,name='member_detail'),
    path('issue_detail/<int:member_id>',views.issue_detail,name='issue_detail'),
    path('add_member/', views.add_member, name='add_member'),
    path('update_member/<int:id>', views.update_member, name='update_member'),
    path('delete_member/<int:id>/',views.delete_member,name='delete_member'),
    path('issue_book/<int:member_id>', views.issue_book, name='issue_book'),
    path('return_book/<int:id>', views.return_book, name='return_book'),
    path('profile/',views.profile,name='profile'),
    path('viewmember/<slug:user>/',views.viewmember,name='viewmember'),
#    path('search/',views.search,name='search'),
]

urls.py
from django import views
from django.contrib import admin
from django.urls import path, include
from libapp import views
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('libapp.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

libapp/models.py
from datetime import datetime, timedelta
from django.db import models

# Create your models here.

class Book(models.Model):

    def __str__(self):
        return self.bname

    bname = models.CharField(max_length=100)
    authorname = models.CharField(max_length=100, null=True)
    bookdesc = models.CharField(max_length=255, null=True)
    price = models.IntegerField()
    stock = models.IntegerField()
    book_category = models.CharField(max_length=20, null=True)
    book_image = models.ImageField(default='default.jpg', upload_to='book_images/')


class Member(models.Model):

    def __str__(self):
        return self.name

    MTYPE = (
            ('student', 'Student'),
            ('teacher', 'Teacher')
            )

    name = models.CharField(max_length=100, null=True)
    email = models.CharField(max_length=100, null=True)
    phone = models.CharField(max_length=100, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    type = models.CharField(max_length=7, choices=MTYPE, default='Student')
    member_image = models.ImageField(default='default.jpg', upload_to='book_images/')    


def get_duedate():
    return datetime.today() + timedelta(days=15)
class IssueDetail(models.Model):
    
    def __str__(self):
        return str(self.member)

    member = models.ForeignKey(Member, null=True, on_delete=models.SET_NULL)
    bname = models.CharField(max_length=100, null=True)
    issue_date = models.DateField()
    due_date = models.DateField(default=get_duedate)
    
    

#class Staff(models.Model):

#    staffid = models.IntegerField(default=0, null=True)
#    staffname = models.CharField(max_length=100)
#    loginid = models.CharField(default=' ', max_length=20, null=True)
#    loginpwd = models.CharField(default=' ', max_length=20, null=True)

libapp/forms.py
from django.forms import ModelForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


from .models import Book, IssueDetail, Member

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['bname', 'authorname', 'bookdesc', 'price', 'stock', 'book_category', 'book_image']

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

MTYPE = (
            ('student', 'Student'),
            ('teacher', 'Teacher')
            )

class MemberForm(forms.ModelForm):
    name = forms.CharField(max_length=100)
    email = forms.CharField(max_length=100)
    phone = forms.CharField(max_length=100)
    date_created = forms.DateTimeField()
    member_image = forms.ImageField()
    type = forms.MultipleChoiceField(required=False, widget=forms.CheckboxSelectMultiple,choices=MTYPE)
    
    class Meta:
        model = Member
        fields = '__all__'

            
class IssueDetailForm(forms.ModelForm):
    member_choices = Member.objects.all()
    member = forms.CharField(label='Member', widget=forms.Select(choices=member_choices))
    bname = forms.CharField(max_length=100)
    issue_date = forms.DateField()
    due_date = forms.DateField()

    class Meta:
        model = IssueDetail        
        fields = ['member', 'bname', 'issue_date', 'due_date']


#class IssueDetailForm(forms.ModelForm):
#    member = forms.ModelChoiceField(queryset=Member.objects.all())

#    class Meta:
#        model = IssueDetail        
#        fields = ['member', 'type', 'bname', 'issue_date', 'due_date']

libapp/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout

from django.contrib import messages
from django.contrib.auth.decorators import login_required
import datetime
from datetime import date
from django.utils.timesince import timesince

# Create your views here.
from .models import Book, Member, IssueDetail
from .forms import BookForm, CreateUserForm, MemberForm, IssueDetailForm
from .filters import BookFilter

#def index(request):
#    return HttpResponse("<h1>Welcome to National Library Management System</h1>")

def index(request):    
    return render(request, 'libapp/welcome.html')

def registerPage(request):
    if request.user.is_authenticated:
        return redirect('/')
    else:
        form = CreateUserForm()

        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, "Account was created for " + user)

                return redirect('/login/')

        context = {'form':form}
        return render(request, 'libapp/register.html', context)

def loginPage(request):
    if request.user.is_authenticated:
        return redirect('/')
    else:
        if request.method == "POST":
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('/profile/')
            else:
                messages.info(request, 'Username OR Password is incorrect')
                
        context = {}
        return render(request, 'libapp/login.html', context)

def adminloginPage(request):
    if request.user.is_authenticated:
        return redirect('/')
    else:
        if request.method == "POST":
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('/books')
            else:
                messages.info(request, 'Username OR Password is incorrect')
                
        context = {}
        return render(request, 'libapp/admin_login.html', context)

def logoutUser(request):
    logout(request)
    return redirect('/')
    
#@login_required(login_url='/admin')
def books(request):
    book_list = Book.objects.all()
    myFilter = BookFilter(request.GET, queryset=book_list)
    book_list = myFilter.qs
    
    context = {'myFilter' : myFilter, 'book_list' : book_list}
    return render(request, 'libapp/index.html', context)

#@login_required(login_url='/admin')
def detail(request, book_id):
    book = Book.objects.get(id=book_id)
    return render(request, 'libapp/detail.html', {'book': book})

#@login_required(login_url='/admin')
def add_book(request):
    if request.method == 'POST':
        bname = request.POST.get('bname',)
        authorname = request.POST.get('authorname',)
        bookdesc = request.POST.get('bookdesc',)
        price = request.POST.get('price',)
        stock = request.POST.get('stock',)
        book_category = request.POST.get('book_category',)
        book_image = request.FILES['book_image']

        book = Book(bname=bname, authorname=authorname, bookdesc=bookdesc, price=price, stock=stock, book_category=book_category, book_image=book_image)
        book.save()
                
    return render(request, 'libapp/add_book.html')

#@login_required(login_url='/admin')
def update(request, id):
    book = Book.objects.get(id=id)
    form = BookForm(request.POST or None, request.FILES, instance=book)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'libapp/edit.html', {'form':form, 'book':book})

#@login_required(login_url='/admin')
def delete(request,id):
    if request.method=="POST":
        book = Book.objects.get(id=id)
        book.delete()
        return redirect('/')
    return render(request,'libapp/delete.html')


#@login_required(login_url='/admin_login/')
def profile(request):
    return render(request, 'libapp/profile.html')

def member_detail(request, id):
    member = Member.objects.get(id=id)
    context = {'member' : member}
    return render(request, 'libapp/member_details.html', context)

def viewmember(request, user):
    member = Member.objects.get(name=user)
    context = {'member' : member}
    return render(request, 'libapp/viewmember.html', context)

#@login_required(login_url='/admin_login/')
def members(request):
    member_list = Member.objects.all()
    context = {'member_list' : member_list}
    return render(request, 'libapp/members.html', context)


#@login_required(login_url='/admin_login/')
def issue_detail(request, member_id):
    member = Member.objects.get(id=member_id)
    li=[]
    details = IssueDetail.objects.filter(member_id=member)
    member_name = details.first()
#    member_type = member_name.type
    book_count = details.count()
    today = date.today()
    detail_list = list(IssueDetail.objects.filter(member_id=member))
    i=0
    for detail in detail_list:
        if detail_list[i].due_date < today:
            t=(detail_list[i].id,
                detail_list[i].bname,
                detail_list[i].issue_date,
                detail_list[i].due_date,
                'Due Date has crossed by',
                (today-detail_list[i].due_date).days,
                ((today-detail_list[i].due_date).days)*2)
        else:
            t=(detail_list[i].id,
                detail_list[i].bname,
                detail_list[i].issue_date,
                detail_list[i].due_date,
                'Due Date is yet to come',
                (detail_list[i].due_date-today).days,
                0)
        i=i+1
        li.append(t)
    context = {'details': details, 'book_count': book_count, 'member_name': member_name, 
                'today':today, 'li':li}
    return render(request, 'libapp/issue_detailsnew.html', context)    


#@login_required(login_url='/admin_login/')
def add_member(request):
    if request.method == 'POST':
        name = request.POST.get('name',)
        email = request.POST.get('email',)
        phone = request.POST.get('phone',)
        date_created = request.POST.get('date_created',)    
        type = request.POST.get('type',)
        member_image = request.FILES['member_image']

        member = Member(name=name, email=email, phone=phone, date_created=date_created, type=type, member_image=member_image)
        member.save()
        
    return render(request, 'libapp/add_member.html')

#@login_required(login_url='/admin_login/')
def update_member(request, id):
    member = Member.objects.get(id=id)
    form = MemberForm(request.POST or None, request.FILES, instance=member)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'libapp/update_member.html', {'form':form, 'member':member})

#@login_required(login_url='/admin_login/')
def delete_member(request,id):
    if request.method=="POST":
        member = Member.objects.get(id=id)
        member.delete()
        return redirect('/')
    return render(request,'libapp/delete_member.html')

#@login_required(login_url='/admin_login/')
def issue_book(request, member_id):
    member_list = Member.objects.all()
    newmember = member_list.get(id=member_id)
    if request.method == 'POST':
        
        bname = request.POST.get('bname',)
        issue_date = request.POST.get('issue_date',)
        due_date = request.POST.get('due_date',)
        
        detail = IssueDetail.objects.create(member=newmember, bname=bname, issue_date=issue_date, due_date=due_date)
        detail.save()   
        messages.success(request, "Book issued successfully")
        
    return render(request, 'libapp/issue_book.html', {'member_list':member_list, 'messages':messages})

#@login_required(login_url='/admin_login/')
def return_book(request, id):
    if request.method=="POST":
        detail = IssueDetail.objects.get(id=id)
        detail.delete()
        return redirect('/')
    return render(request,'libapp/return_book.html')


#def search(request):
#    if request.method=="POST":
#        searched = request.POST['searched']
#        authors = Book.objects.filter(authorname__contains=searched)
#        return render(request, 'libapp/search.html', {'searched':searched, 'authors':authors})
#    else:
#        return render(request, 'libapp/search.html', {})
    
    

libapp/templates/libapp/add_book.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <input type="text" name="bname" id="name" placeholder="Enter name of the book"><br><br>
    <input type="text" desc="authorname" id="authorname" placeholder="Enter name of the author"><br><br>
    <input type="text" desc="bookdesc" id="bookdesc" placeholder="Enter book description"><br><br>
    <input type="text" name="price" id="price" placeholder="Enter price of the book"><br><br>
    <input type="text" name="stock" id="stock" placeholder="Enter book stock"><br><br>
    <input type="text" desc="book_category" id="book_category" placeholder="Enter book category"><br><br>
    <input type="file" name="book_image" id="book_image"><br><br>
    <input type="submit" value="Submit">

</form>

libapp/templates/libapp/add_member.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <input type="text" name="name" id="name" placeholder="Enter member's name"><br><br>
    <input type="email" name="email" id="email" placeholder="Enter member's email"><br><br>
    <input type="tel" name="phone" id="phone" placeholder="Enter member's phone"><br><br>
    <input type="date" name="date_created" id="date_created" placeholder="Enter joined date"><br><br>
    <input type="text" name="type" id="type" placeholder="Enter member type-Student/Teacher"><br><br>
    <input type="file" name="member_image" id="member_image">
    <input type="submit" value="Submit">

    
    
</form>

libapp/templates/libapp/admin_login.html
{% extends 'libapp/base.html' %}

{% block body %}

<!DOCTYPE html>
<html>
    
<head>
	<title>Admin Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">ADMIN-LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'libapp:register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>
{% endblock %}

libapp/templates/libapp/delete.html
<form method="POST">
    {% csrf_token %}
    Are you sure you want to delete this book?
    <input type="submit">
</form>

libapp/templates/libapp/login.html
{% extends 'libapp/base.html' %}

{% block body %}

<!DOCTYPE html>
<html>
    
<head>
	<title>Student-Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">STUDENT-LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'libapp:register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>
{% endblock %}

libapp/templates/libapp/member_details.html
{% extends 'libapp/admin_navbar.html' %} 
{% block body %}

<br>

<div class="row">
	<div class="col-md">
		<div class="card card-body">
			<h5>Member: {{member.name}}</h5>
			<h5>Type  : {{member.type}}</h5>
			<hr>
			<a class="btn btn-outline-info  btn-sm btn-block" href="{% url 'libapp:update_member' member.id %}">Update Member</a>
			<a class="btn btn-outline-info  btn-sm btn-block" href="{% url 'libapp:delete_member' member.id %}">Delete Member</a>
			<a class="btn btn-outline-info  btn-sm btn-block" href="{% url 'libapp:issue_book' member.id %}">Issue Book</a>
		</div>
	</div>

	<div class="col-md">
		<div class="card card-body">
			<h5>Contact Information</h5>
			<hr>
			<p>Email      : {{member.email}}</p>
			<p>Phone      : {{member.phone}}</p>
			<p>Joined Date: {{member.date_created}}</p>
		</div>
	</div>
</div>
{% endblock %}

libapp/templates/libapp/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'libapp/style.css' %}">
    <title>Document</title>
</head>
<body>
    <style>
        .hello-msg{
          font-size: 18px;
          color: #000000;
          margin-right: 20px;
        }        
    </style>
  
    <!-- Image and text -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">National Library Management System</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>    
        <span class="hello-msg">Hello, {{request.user}}</span>
        <span ><a class="hello-msg" href="{% url 'libapp:logout' %}">Logout</a></span>
    </nav>
    <div class="container profile">
        <div class="row">
            <div class="col-md-8">
                <div class="profile-tab">
                    <div class="tab-pane">
                        <div class="row">
                            <div class="col-md-6">
                                <label>Username:</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{user}}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Email:</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{user.email}}</p>
                            </div>
                        </div>
                        <a class="btn btn-outline-info  btn-sm btn-block" href="{% url 'libapp:viewmember' user %}">View Member Details  </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

libapp/templates/libapp/viewmember.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'libapp/style.css' %}">
    <title>Document</title>
</head>
<body>
    <style>
        .hello-msg{
          font-size: 18px;
          color: #000000;
          margin-right: 20px;
        }        
    </style>
  
    <!-- Image and text -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">National Library Management System</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>    
        <span class="hello-msg">Hello, {{request.user}}</span>
        <span ><a class="hello-msg" href="{% url 'libapp:logout' %}">Logout</a></span>
    </nav>
    <center>
        <img width="250" height="250" src="{{member.member_image.url}}">
    </center>
    <hr>
    <hr>
    <div class="container profile">
        <div class="row">
            <div class="col-md-8">
                <div class="profile-tab">
                    <div class="tab-pane">
                        <div class="row">
                            <div class="col-md-6">
                                <label>Member:</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{member.name}}</p>
                            </div>
                            <div class="col-md-6">
                                <label>Type:</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{member.type}}</p>
                            </div>
                            <div class="col-md-6">
                                <label>Email:</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{member.email}}</p>
                            </div>
                            <div class="col-md-6">
                                <label>Phone:</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{member.phone}}</p>
                            </div>
                            <div class="col-md-6">
                                <label>Joined Date:</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{member.date_created}}</p>
                            </div>
                    
                            <a class="btn btn-outline-info  btn-sm btn-block" href="{% url 'libapp:update_member' member.id %}">Update Member</a>
                            <a class="btn btn-outline-info  btn-sm btn-block" href="{% url 'libapp:issue_detail' member.id %}">View Issued Books</a>
                            <a class="btn btn-outline-info  btn-sm btn-block" href="{% url 'libapp:books' %}">Search Books</a>
                        </div>                           
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>